[tracker]
patches_repo = "rushiranpise/morphe-patches"
constants_path = "patches/src/main/kotlin/app/template/patches/shared/Constants.kt"
release_prefix = "tracker"
work_dir = ".work"
target_branch = "dev"
parallel_jobs = 4

[cli]
repo = "MorpheApp/morphe-cli"
asset_regex = ".*\\.jar$"
prerelease = false

[patches]
repo = "rushiranpise/morphe-patches"
asset_regex = ".*\\.(mpp|rvp|jar)$"
prerelease = false

[splitwise]
enabled = true
app-name = "Splitwise"
package-name = "com.Splitwise.SplitwiseMobile"
constant = "SPLITWISE_COMPATIBILITY"
current-version = "26.5.5"
version = "latest"
arch = "all"
dpi = "nodpi anydpi auto"
apk-types = "apk xapk apks"
apkmirror-dlurl = "https://www.apkmirror.com/apk/splitwise/splitwise"
apkcombo-dlurl = "https://apkcombo.com/search/com.Splitwise.SplitwiseMobile/"
uptodown-dlurl = "https://splitwise.en.uptodown.com/android"
